name: CI

on:
  push:
  pull_request:

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry virtualenvs
        run: poetry config virtualenvs.create true

      - name: Install dependencies (with dev)
        run: poetry install --with dev

      - name: Ruff (lint)
        run: poetry run ruff check .

      - name: Black (format check)
        run: poetry run black --check .

      - name: Pytest
        run: poetry run pytest -q

      - name: Secret scan
        run: poetry run python scan_secrets.py --skip-outputs --out secrets_report.md

      - name: Upload secrets report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: secrets-report
          path: secrets_report.md
